### ISSUE TITLE
Gd rc 1 breaks godot rust

### ISSUE THREAD

**Issue by Coder2195Text** [godot-rust/gdextension#119]
```
error: failed to run custom build command for `godot-core v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#b2f75f8c)`
Caused by:
  process didn't exit successfully: `/home/coder2195/projects/rust/tile-craft/target/debug/build/godot-core-50e8836cddd65a35/build-script-build` (exit status: 101)
  --- stdout  cargo:rerun-if-changed=/home/coder2195/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/b2f75f8/godot-codegen/input/gen/extension_api.json
  Found 'godot4' executable in PATH: /home/coder2195/godot/godot4  cargo:rerun-if-changed=/home/coder2195/godot/godot4
  Godot version: 4.0.rc1.official.8843d9ad3

  --- stderr
  thread 'main' panicked at 'failed to parse Godot version '4.0.rc1.official.8843d9ad3
  ': Version substring cannot be parsed: `4.0.rc1.official.8843d9ad3
  `', /home/coder2195/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/b2f75f8/godot-codegen/src/godot_exe.rs:87:13  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

**Comment by Bromeon** [comment]
This is the _third_ time you open a duplicate issue in this repository (#82, #87).

Can you **please** spend 5 minutes to check the issue tracker?
Issue #118 is literally one number lower than this one.

Thanks for your understanding.

**Comment by Bromeon** [comment]
I need to apologize for wrongly classifying this as `duplicate` and my comment that this happened the 3rd time. Nevertheless, I'd appreciate for the future (not in this case) to check the issue tracker and latest `master` version. Thanks!

**Comment by Coder2195Text** [comment]
> I need to apologize for wrongly classifying this as `duplicate` and my comment that this happened the 3rd time. Nevertheless, I'd appreciate for the future (not in this case) to check the issue tracker and latest `master` version.
> 
> Thanks for reporting!

its fine lol everyone makes mistakes
