### ISSUE TITLE
How to make self into Gd<Self> type

### ISSUE THREAD

**Issue by yIllusionSky** [godot-rust/gdextension#129]
Code:
```
fn ready(&mut self){
        self.animation_player = self.try_get_node_as::<AnimationPlayer>("AnimationPlayer");

        if let Some(animation_player) = self.animation_player.as_mut() {
            animation_player.play("TextPlayer".into(), -1.0, 1.0, false);
        
           //Here
            **animation_player.connect("animation_finished".into(), Callable::from_object_method(*self, "end"), 0);**
            
        }
        
    }
```
Question:
I need to bind the animation signal to a slot of my own, but the slot needs a Gd<T> parameter, I only have one self, how do I solve it。

**Comment by indubitablement2** [comment]
With `self.base.share()`. Also consider checking out discord [https://discord.gg/aKUCJ8rJsc](url). For small question you may get an anwer faster there.

**Comment by yIllusionSky** [comment]
> 和 `self.base.share()`. 还可以考虑检查不和谐。 对于小问题，您可能会在那里更快地得到答案。

thanks，problem solved

**Comment by ISibboI** [comment]
Thank you for not posting this on discord, because this way I could find it via a search engine!
