### ISSUE TITLE
Add a `real` type

### ISSUE THREAD

**Issue by sayaks** [godot-rust/gdextension#135]
Currently a lot of struct and functions in rust are hard-coded to use `f32`s. Such as `Vector2`, `Vector3` etc. But in godot these structs and functions may be either `float` or `double` depending on whether godot is compiled with `precision=double` or not.

In godot the type used is called `real_t` and will be either a `float` or `double`. We could do the same in our bindings. As it is, our bindings will likely break if we try to use it with a godot that is compiled with `precision=double` enabled.

The `float` type in godot, and thus the one used by variant, is always a `double`, see: https://docs.godotengine.org/en/stable/classes/class_float.html.

**Comment by Bromeon** [comment]
[godot-cpp](https://github.com/godotengine/godot-cpp/) could also serve as an inspiration here.

**Comment by ttencate** [comment]
This is what godot-cpp does:

https://github.com/godotengine/godot-cpp/blob/9d1c396c54fc3bdfcc7da4f3abcb52b14f6cce8f/include/godot_cpp/core/defs.hpp#L102-L106

This `REAL_T_IS_DOUBLE` is set manually through scons when compiling godot-cpp, using a `precision=double` option just like the engine itself:

https://github.com/godotengine/godot-cpp/blob/2b7094f342beb11166f86a6309bba86fe4b21838/SConstruct#L207-L208

In our case, maybe we could even detect it from the Godot binary and generate the appropriate code?

**Comment by sayaks** [comment]
> In our case, maybe we could even detect it from the Godot binary and generate the appropriate code?

i couldn't really find a way to reliably detect it from the godot binary, but if you can find something that'd be useful! currently i've just added a feature called `precision-double` in #149.

**Comment by Bromeon** [comment]
Regarding detection, I got this answer from Godot devs:

>  There are feature tags called `single` and `double` that you can add to your *.gdextension file to make sure Godot loads the correct library
> 
> If you want to check it at runtime, then something like `OS::get_singleton()->has_feature("double")`
> should probably work
> Although I guess you probably wouldn't get to that point, if you try to do it from a library expecting a single-precision ABI while using a double-precision engine build or vice versa, so using the feature tags and separate libraries are probably your best bet
