### ISSUE TITLE
x, y, and z properties do not exist in Basis object

### ISSUE THREAD

**Issue by atrefonas** [godot-rust/gdextension#141]
I noticed that Basis has col_a(), col_b(), and col_c() while Godot you can do basis.x, basis.y, and basis.z. This is somewhat confusing. I guess col_a() is probably the same thing as basis.x?

https://docs.godotengine.org/en/latest/classes/class_basis.html

**Comment by Bromeon** [comment]
Please check the documentation before opening issues. This is part of every method description.
```rs
/// Returns the first column of the matrix,
    ///
    /// _Godot equivalent: `Basis.x`_
    #[must_use]
    pub fn col_a(&self) -> Vector3 {
        Vector3::new(self.rows[0].x, self.rows[1].x, self.rows[2].x)
    }
```

Regarding the reasoning: it's arguable what is confusing. Naming column vectors `x`, `y` and `z` also has potential to be misunderstood, as it has nothing to do with the X, Y, Z coordinates. They are three axis in any directions.
