### ISSUE TITLE
returning `Variant` from functions doesn't work

### ISSUE THREAD

**Issue by the-ssd** [godot-rust/gdextension#163]
```rust
#[func]
pub fn ret_var(&self) -> Variant{
    return 0.to_variant();
}
```
when running Godot says that `ret_var` returns void

**Comment by Bromeon** [comment]
Please check the issue tracker, this has been already reported: https://github.com/godot-rust/gdextension/issues/159

**Comment by the-ssd** [comment]
sorry, I checked but i guess I am blind
