### ISSUE TITLE
GDExtension API has changed ! (a bit)

### ISSUE THREAD

**Issue by touilleMan** [godot-rust/gdextension#19]
This is friendly note so that you don't freak out when seeing this project it broken against Godot's master :smiley:

see https://github.com/godotengine/godot/pull/67750 & https://github.com/godotengine/godot-cpp/pull/896

Basically GDExtension API uses `StringName` (almost) everywhere instead of the `char *`. On top of that the [way to register proerties has been simplified](https://github.com/godotengine/godot/pull/67750#issuecomment-1288092181).

**Comment by Bromeon** [comment]
Thanks for the heads-up! 👍 

No worries, [change detection of the GDExtension header has already been automated](https://github.com/godot-rust/gdextension/actions/runs/3354654238#summary-9185759738), outputting a descriptive diff 😉

Nevertheless it's of even nicer to have a descriptive changeset, so I appreciate being proactive! I also wrote a comment regarding https://github.com/godotengine/godot/issues/61968, which might now be mitigated or even fully solved.

**Comment by Bromeon** [comment]
> however it would be even better to entirely remove the `get_property_list` an replace it by an array passed where `get_property_list` function pointer is currently provided.

You mean when the class is registered, one would provide an array of all properties?

I think that might be ideal, because then the extension library can forget (aka deallocate) the property meta-information once registered. I might need to check the implementation to make sure I'm not missing something though 🙂

**Comment by touilleMan** [comment]
@Bromeon see https://github.com/godotengine/godot/pull/68479 ;-)
