### ISSUE TITLE
cargo build error `use godot::engine::{file_access, os};  no `file_access` in `engine` `

### ISSUE THREAD

**Issue by adminSxs** [godot-rust/gdextension#39]
os: Win11 21H2
rust toolchain: stable-x86_64-pc-windows-msvc
clang: 14.0.4
gotdot4: Godot_v4.0-beta1_win64.exe

i have setup requirement,when i was start build this project,occur below build error:

![image](https://user-images.githubusercontent.com/15902505/204943126-ec9cfa39-8104-46cd-ab2b-16fc9ff78683.png)

**Comment by Bromeon** [comment]
> gotdot4: Godot_v4.0-beta1_win64.exe

This version is too old. Can you try Beta 5?

**Comment by adminSxs** [comment]
> > gotdot4: Godot_v4.0-beta1_win64.exe
> 
> This version is too old. Can you try Beta 5?

thanks, use godot master branch code to build godot engine,and rebuild gdextension successfuil!!

**Comment by Bromeon** [comment]
Great to hear, thanks for checking!
