### ISSUE TITLE
Rust analyzer cannot recognize on Gd<T>

### ISSUE THREAD

**Issue by Hapenia-Lans** [godot-rust/gdextension#41]
This is a piece of the example "dodge-the-creeps"

![image](https://user-images.githubusercontent.com/93276898/205421358-b105a6a6-1535-455f-bfc9-2e11452daa64.png)

Type recognition seems to have gone wrong.

**Comment by Bromeon** [comment]
The symbol database doesn't work as expected with the current path for generated files.
See #40 which was just opened a few hours before yours 🙂
