### ISSUE TITLE
Encounter the problem of cargo build

### ISSUE THREAD

**Issue by yaoye6262** [godot-rust/gdextension#44]
error: failed to run custom build command for `godot-ffi v0.1.0 (https://github.com/godot-rust/gdextension?branch=master#eaefd45d)`

Caused by:
  process didn't exit successfully: `/Users/outao/Documents/GoDotRust/JumpNewGame/game-lib/target/debug/build/godot-ffi-f35a8badc2c742e5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=../godot-codegen/input/gdnative_interface.h

  --- stderr
  Build selected for macOS.
  thread 'main' panicked at 'env var 'LLVM_PATH' not set: NotPresent', /Users/outao/.cargo/git/checkouts/gdextension-25c68fb170a9fb9d/eaefd45/godot-ffi/build.rs:64:42
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by Coder2195Text** [comment]
try this https://rust-lang.github.io/rust-bindgen/requirements.html#windows
