### ISSUE TITLE
Access is denied when running cargo build on gdextension folder

### ISSUE THREAD

**Issue by PizzaCutter** [godot-rust/gdextension#52]
**Issue:**
I'm getting a error when running "cargo build" command in the gdextension folder. Seems like windows is blocking the access to godot but not really sure how to resolve it. I've tried running the command from command prompt in both admin mode and non-admin mode and tried the same thing via powershell. Also tried restarting my computer to make sure windows wasn't locking the godot executable for some reason. 

**Clang Version:**
clang version 15.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

**Rust Version:**
rustc 1.65.0 (897e37553 2022-11-02)

**Full error:**
error: failed to run custom build command for `godot-ffi v0.1.0 (D:\Godot\gdextension\godot-ffi)`

Caused by:
  process didn't exit successfully: `D:\Godot\gdextension\target\debug\build\godot-ffi-82ae7c24a43616ed\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=../godot-codegen/input/gdnative_interface.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\15.0.6\include\stddef.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\15.0.6\include/__stddef_max_align_t.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\15.0.6\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\stdint.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\sal.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\concurrencysal.h
  cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\15.0.6\include\vadefs.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vadefs.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\stdio.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_wstdio.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_stdio_config.h
  cargo:rerun-if-changed=C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h
  cargo:rerun-if-changed=D:\Godot\gdextension\godot-codegen/input/gen/extension_api.json
  Found GODOT4_BIN with path to executable: 'D:\Godot\Godot_v4.0-beta1_win64.exe'
  cargo:rerun-if-changed=D:\Godot\Godot_v4.0-beta1_win64.exe

  --- stderr
  Build selected for Linux/Windows.
  thread 'main' panicked at 'failed to invoke Godot executable 'D:\Godot\Godot_v4.0-beta1_win64.exe': Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', godot-codegen\src\godot_exe.rs:66:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by PizzaCutter** [comment]
Windows defender is active but no other antivirus software is installed. Tried turning off windows defender realtime protected but still getting the same error code.

**Comment by Bromeon** [comment]
Can you call the Godot executable from the `cmd` terminal?

Also, `Godot_v4.0-beta1_win64.exe` is far too old -- you need a recent Beta version, or better even, nightly.

In any case, this seems to be a problem with your Windows setup rather than with godot-rust. I recommend searching on the Internet for more specific advice -- a good starting point [might be here](https://support.microsoft.com/en-us/topic/-access-denied-or-other-errors-when-you-access-or-work-with-files-and-folders-in-windows-219af563-1953-ab4a-f17e-b0182755214e), for example.

**Comment by Bromeon** [comment]
Closing as the problem seems unrelated to godot-rust.
