### ISSUE TITLE
Custom mainloop can't work

### ISSUE THREAD

**Issue by Hapenia-Lans** [godot-rust/gdextension#58]
Custom mainloop can't work properly. Refers to [this issue](https://github.com/godotengine/godot/issues/70764). kleonc's solution can work with gdscript mainloop, but rust's failed.

The minimal reproduction project is in the linked issue above. And the rust part is simply add these:

Here is `my_main_loop.rs`:

```rust
use godot::prelude::*;

#[derive(GodotClass, Debug)]
#[class(base=SceneTree)]
pub struct MyMainLoop {
    #[base]
    base: Base<SceneTree>,
}

#[godot_api]
impl MyMainLoop {
    #[func]
    fn say_hello(&self) {
        godot::prelude::godot_print!("hello world!");
    }
}

#[godot_api]
impl GodotExt for MyMainLoop {

}
```

Here `lib.rs`:

```rust

use godot::prelude::*;

struct ExtMain;

mod my_mainloop;

#[gdextension]
unsafe impl ExtensionLibrary for ExtMain {}

```

**Comment by Hapenia-Lans** [comment]
My guess is that there was an error somewhere in the class registration or binding process.

**Comment by Bromeon** [comment]
Just to clarify: there is nothing that godot-rust could do here, right?
We need to wait for an fix in Godot itself?

**Comment by Bromeon** [comment]
@Hapenia-Lans any answer to my question above? 🙂

**Comment by Hapenia-Lans** [comment]
Closed. Something went wrong if you don't override `init()` function. Add the code below can fix this. Maybe it should be another issue.

```rust
#[godot_api]
impl GodotExt for MyMainLoop {
    fn init(base: Base<SceneTree>) -> Self {
        Self { base }
    }
}
```
