### ISSUE TITLE
#[godot_api]: calls to `std::mem::forget` with a value that implements `Copy`. Forgetting a copy leaves the original intact

### ISSUE THREAD

**Issue by lecoqjacob** [godot-rust/gdextension#80]
Going off the `dodge-the-creeps` example, deriving #[godot_api] causes the following warning message to display:

`calls to `std::mem::forget` with a value that implements `Copy`. Forgetting a copy leaves the original intact`

![image](https://user-images.githubusercontent.com/9278174/213887903-f920291e-e5a3-4f48-b4e0-7bf1f15a2fbd.png)

**Comment by Bromeon** [comment]
Thanks for the report! I should probably include `cargo check` (or even `cargo clippy`) for examples in CI.

**Comment by Bromeon** [comment]
This should be fixed with #74.
