### ISSUE TITLE
Classes with base of `HttpRequest` fail to register

### ISSUE THREAD

**Issue by justofisker** [godot-rust/gdextension#88]
When attempting to create a class that extends `HttpRequest` it fails to register and outputs and error.

Simple class that extends `HttpRequest`.
```rs
use godot::engine::{HttpRequest};
use godot::prelude::*;

#[derive(GodotClass)]
#[class(base=HttpRequest)]
pub struct TestHTTP {
    #[base]
    base: Base<HttpRequest>,
}

#[godot_api]
impl GodotExt for TestHTTP {
    fn init(base: Base<HttpRequest>) -> Self {
        TestHTTP {
            base,
        }
    }
}
```

Error when attempt to run project.
```
E 0:00:00:0400   _register_extension_class: Attempt to register an extension class 'TestHTTP' using non-existing parent class 'HttpRequest'
  <C++ Error>    Method/function failed.
  <C++ Source>   core/extension/gdextension.cpp:263 @ _register_extension_class()
```

If I change the base type to `Node` or `Control` it works fine.

**Comment by Coder2195Text** [comment]
> What do you mean with "not recognized by Godot"?

I think they mean like showing up as a extended node in the list that appears when u choose node types

**Comment by justofisker** [comment]
> What do you mean with "not recognized by Godot"?

I cannot reference the class type in code or create a node of it's type in the editor. I was getting an error message at some point I'll try to cause it again and post it here.

**Comment by justofisker** [comment]
I get this error, when I run the project from the editor.

```
E 0:00:00:0400   _register_extension_class: Attempt to register an extension class 'TestHTTP' using non-existing parent class 'HttpRequest'
  <C++ Error>    Method/function failed.
  <C++ Source>   core/extension/gdextension.cpp:263 @ _register_extension_class()
```

**Comment by Coder2195Text** [comment]
> I get this error, when I run the project from the editor.
> 
> ```
> E 0:00:00:0400   _register_extension_class: Attempt to register an extension class 'TestHTTP' using non-existing parent class 'HttpRequest'
>   <C++ Error>    Method/function failed.
>   <C++ Source>   core/extension/gdextension.cpp:263 @ _register_extension_class()
> ```

this might be more suited for godotengine/godot itself, because that is core Godot Api stuff

**Comment by Bromeon** [comment]
This was indeed a bug on our side, it's not Godot's responsibility to accept case-insensitive class names.
Thanks for reporting!
